### ISSUE TITLE
repeatedly transferring npc_dota_ghost_bane's nightmare will crash the game

### ISSUE THREAD

**Issue by DankBudd** [roberthorvers/Hoard_Mode#36]
only happens with the bane creep, the hero bane should be fine.

it seems to happen only when transferred back and forth between 2 heroes
if theres is more than 2 heroes in the mix it wont crash

**Comment by Htresnal** [comment]
Just retested this bug(with Lone Druid and his Spirit Bear), and it is still present. Seems like bane's death may be the reason(same way the old Doom skill was crashing the game after Spooki's death).

It crashes not because you switch it too fast, but because you prolong it enough for bane creep to despawn completely.
