### ISSUE TITLE
Underlord's passive is overpowered

### ISSUE THREAD

**Issue by Htresnal** [roberthorvers/Hoard_Mode#70]
Damage reduce aura is too effective versus bosses.

**Comment by DankBudd** [comment]
thats debatable, since most bosses are getting inventory's now they have items that give bonus damage. so they still deal decent damage even if their base damage is being reduced.

Edit: actually im not so sure, i had the skeleton boss in mind when i said that. a sacred relic(+60 damage) doesnt really compensate for that 40% reduction on underlords aura.
maybe making the skill have a separate reduction value for bosses would be a good idea.
