### ISSUE TITLE
Sniper with Dragon Lance

### ISSUE THREAD

**Issue by Htresnal** [roberthorvers/Hoard_Mode#80]
Is able to take down the whole Dire base solo(using Q to show the tower), as his range goes greater than Mega tower's range.
Workaround:
Huskar's passive style skill, which, instead of attack speed, would increase tower's attack range.
OR
Every time someone attacks the mega tower, it gains the attack range similar to the distance between the attacker and the tower itself. Can't go lower than 1k. Will lose the bonus attack range after 30 seconds.

Its pretty slow, so I'm not quite sure if its a feature or a cheat..

**Comment by DankBudd** [comment]
well i mean, sniper is supposed to be the only hero in dota with crazy attack range (other than techies/lina), his whole bit is attack range which doesnt really help in horde mode other than in pushing towers.
i think its reasonable that he can attack the mega towers from outside their attack range.

**Comment by Htresnal** [comment]
We need to make a "sniper the fast pusher" challenge. Build desol+rapier asap and see, how long would it take for him to raze everything down, including the dire ancient. If that would be possible in less than 20-22 minutes, then its definitely a cheat.. otherwise it may live the way it exists now.

**Comment by DankBudd** [comment]
theres really no strat with just sniper that could work within a 25 min time frame. 
farming a deso and rapier that early is pretty difficult without stealing all the farm, and even if you did take all the farm you probably wouldnt be able to destroy the enemy ancient before your team gets overrun.

you might be able to pull it off with multiple heroes that are good at pushing, but if it requires 3+ heroes then its not really an OP strat.

there used to be broken strats like that with heroes like windranger and her 100% evasion and ult, but most if not all of that stuff has been dealt with since the towers got buffed.
