### ISSUE TITLE
Cost nerfs

### ISSUE THREAD

**Issue by Htresnal** [roberthorvers/Hoard_Mode#91]
I feel like some item cost rebalance may positively affect the gameplay:

Sange, Yasha and Atos:
- Remove recipe. (-1000 total gold cost).

King Rapier:
- Reduce recipe cost down to 2400 (-600 gold) - Feels unfairly costly, considering the difficulty growth. Sometimes, it feels better to buy a second rapier, instead of finishing the current one.

Vladmir's Cuirass:
- Reduce recipe cost down to 1800 (-700 gold) - High recipe cost forces carries to balance between finishing the Vlad's Cuirass now, but have no damage to fight creeps off, or don't finish it until the very late game, since recipe is almost half cost of the Divine Rapier.

War Fury:
- Reduce recipe cost down to 1200 (-800 gold) - Low damage bonus and low cleave bonus simply won't cut in with the high cost of the recipe:
1) Quell bonus doesn't work against buildings.
2) Quell bonus damage works only with the white(base) damage. Base damage is all about high stats growth, or special passives, on heroes like Tiny, Phantom lancer and few other heroes.
3) Hero base damage lingers around 100-150 at the 32nd minute of the game, resulting in about +60 bonus damage.
4) Other heroes have no reason to upgrade their Battle Fury further, its more profitable to buy Divine Rapier asap.

**Comment by Diellan** [comment]
I agree regarding SnYnA, and we also need to do a pass over its active ability to make sure it follows the new Atos properly.

The King Rapier is still bought incredibly often, so I'm not ready to buff it. Not only does it do more damage, but you no longer get screwed if you die (due to item drop and needing to fish the item back from what is certainly an overrun of mobs).

Vlad 2 can drop. It doesn't provide too much.

War Fury I agree with. Drop it.
